version: '3'

services:
    api:
        build: 
            context: .
        ports:
            - "9000:9000"
        depends_on:
            - mongo
            - redis
        links: 
            - mongo
            - redis
    mongo:
        image: mongo
        volumes:
            - ./data/mongo:/data/db
            
    redis:
        image: redis
        volumes:
            - ./data/redis:/data/db