

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
    port: 9000


spring:

    profiles:
        active: dev

    data:
        # MONGODB (MongoProperties)
        mongodb: 
            host: localhost
            port: 27017
            database: votacao_db
    
    ## REDIS        
    redis:
        host: localhost
        port: 6379
        timeout: 5
        pool:
            min-idle: 1
            max-active: 100


        