
# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
    port: 8080


spring:

    profiles:
        active: docker
   
    data:
        # MONGODB (MongoProperties)
        mongodb: 
            host: mongo
            port: 27017
            database: votacao_db
    
    ## REDIS        
    redis:
        host: redis
        port: 6379
        timeout: 5
        pool:
            min-idle: 1
            max-active: 100


        