

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
    port: 9000


spring:

    profiles:
        active: @spring.profiles.active@


    # SPRING MVC (WebMvcProperties)
    mvc:
        locale: pt_BR
        date-format: dd/MM/yyyy HH:mm:ss
    
    # LOGGING    
    logging:
        level:
            ROOT: ERROR
            org.springframework: ERROR
            org.springframework.data: ERROR
            org.mongodb: ERROR
            br.com.selecaoglobo.votacaoapi: INFO
        pattern:
            console: "%d{dd-MM-yyyy HH:mm:ss} - %msg%n"
    
    #HTTP
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true


## VOTE API
voteapi:
    cache:
        user-token:
            # timeout do cache do user-token em minutos
            timeout: 10
            max-votes: 5
        